global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:9090
        labels:
          app: prometheus
  - job_name: 'spring-boot-app'  # 监控 Spring Boot 应用
    metrics_path: '/api/actuator/prometheus'  # Micrometer 暴露的指标路径
    static_configs:
      - targets: [ 'host.docker.internal:8338' ]  # 应用实例地址
